const capsData = {
  Tram: [
    {
      Company: 'West Midlands Metro',
      Items: [
        {
          Period: 'Day',
          CapName: 'Metro Single Anytime',
          Area: 'All trams',
          AreaLink: '',
          Price: 'From £1.50',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Metro Return Anytime',
          Area: 'All trams',
          AreaLink: '',
          Price: 'From £2.00',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'NX + Metro Day Off Peak',
          Area: 'NX Buses + All Trams',
          AreaLink: '',
          Price: '£5.60',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'nNetwork bus + Metro Day',
          Area: 'All nNetwork bus operators + All Trams',
          AreaLink: '',
          Price: '£6.80',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Metro Day Off Peak',
          Area: 'All nNetwork bus operators + All Trams',
          AreaLink: '',
          Price: '£5.90',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Metro Week',
          Area: 'All trams',
          AreaLink: '',
          Price: '£23.00',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'NX + Metro Week',
          Area: 'NX Busses + All trams',
          AreaLink: '',
          Price: '£25.90',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'nNetwork bus + Metro Week',
          Area: 'All nNetwork bus operators + All trams',
          AreaLink: '',
          Price: '£27.20',
          ChildPrice: '',
        },
      ],
    },
  ],

  Bus: [
    {
      Company: 'Valid on all buses that accept Swift Go',
      Items: [
        {
          Period: 'Day',
          CapName: 'nNetwork Bus Peak',
          Area: 'Regional',
          AreaLink: '',
          Price: '£4.80',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'nNetwork Bus Off-peak',
          Area: 'Regional',
          AreaLink: '',
          Price: '£4.20',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'nNetwork Bus and Metro Peak',
          Area: 'Regional',
          AreaLink: '',
          Price: '£6.80',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'nNetwork Bus and Metro Off-peak',
          Area: 'Regional',
          AreaLink: '',
          Price: '£5.90',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Sandwell and Dudley nNetwork Bus Anytime',
          Area: 'Sandwell and Dudley',
          AreaLink: '',
          Price: '£3.20',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Walsall nNetwork Bus Anytime',
          Area: 'Walsall',
          AreaLink: '',
          Price: '£3.20',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'nNetwork bus Week',
          Area: 'Regional',
          AreaLink: '',
          Price: '£18.40',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'nNetwork bus Off-Peak Week',
          Area: 'Regional',
          AreaLink: '',
          Price: '£14.70',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'nNetwork bus Coventry Week',
          Area: 'Coventry',
          AreaLink: '',
          Price: '£15.80',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'nNetwork bus Coventry Off-Peak',
          Area: 'Coventry',
          AreaLink: '',
          Price: '£12.60',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'nNetwork bus Black Country Week',
          Area: 'Black Country',
          AreaLink: '',
          Price: '£17.00',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'nNetwork bus Sandwell & Dudley Week',
          Area: 'Sandwell & Dudley nNetwork bus',
          AreaLink: '',
          Price: '£11.60',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'nNetwork bus Walsall Week',
          Area: 'Walsall nNetwork bus',
          AreaLink: '',
          Price: '£11.60',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'nNetwork bus+ Metro Week',
          Area: 'nNetwork Bus + Metro',
          AreaLink: '',
          Price: '£27.20',
          ChildPrice: '',
        },
      ],
    },
    {
      Company: 'Arriva',
      Items: [
        {
          Period: 'Day',
          CapName: 'Arriva Single Anytime',
          Area: 'All services in the West Midlands',
          AreaLink: '',
          Price: '£2.40',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Arriva Regional Peak',
          Area: 'All services in the West Midlands',
          AreaLink: '',
          Price: '£4.80',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Arriva Regional Off-peak',
          Area: 'All services in the West Midlands',
          AreaLink: '',
          Price: '£4.20',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Arriva Wolverhampton Anytime',
          Area: 'Wolverhampton service 9',
          AreaLink: '',
          Price: '£4.00',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Arriva West Midlands Week',
          Area: 'All services in the West Midlands',
          AreaLink: '',
          Price: '£18.40',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Arriva West Midlands Week Off-Peak',
          Area: 'All services in the West Midlands',
          AreaLink: '',
          Price: '£14.70',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Arriva Wolverhampton Week',
          Area: 'Wolverhampton service 9',
          AreaLink: '',
          Price: '£17.00',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Arriva Coventry Week',
          Area: 'Coventry',
          AreaLink: '',
          Price: '£15.80',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Arriva Coventry Week Off-Peak',
          Area: 'Coventry',
          AreaLink: '',
          Price: '£12.60',
          ChildPrice: '',
        },
      ],
    },
    {
      Company: 'Banga Buses',
      Description: 'Swift Go is not accepted on the 1X service',
      Items: [
        {
          Period: 'Day',
          CapName: 'Banga Buses Single Anytime',
          Area: 'Services 52 and 53',
          AreaLink: '',
          Price: '£2.40',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Banga Buses Single Anytime',
          Area: 'Services 530 and 545',
          AreaLink: '',
          Price: '£2.10',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Banga Buses Single Anytime',
          Area: 'Service 891',
          AreaLink: '',
          Price: '£2.00',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Banga Buses Day Anytime',
          Area: 'All areas',
          AreaLink: '',
          Price: '£4.20',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Banga Buses Walsall Anytime',
          Area: 'Walsall area',
          AreaLink: '',
          Price: '£3.20',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Banga Buses Sandwell and Dudley Anytime',
          Area: 'Sandwell and Dudley area',
          AreaLink: '',
          Price: '£3.20',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Banga Week',
          Area: 'All areas',
          AreaLink: '',
          Price: '£17.00',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Banga Week Off-Peak',
          Area: 'All areas',
          AreaLink: '',
          Price: '£14.70',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Banga Walsall Week',
          Area: 'Walsall',
          AreaLink: '',
          Price: '£11.60',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Banga Sandwell & Dudley Week',
          Area: 'Sandwell and Dudley area',
          AreaLink: '',
          Price: '£11.60',
          ChildPrice: '',
        },
      ],
    },
    {
      Company: 'Chaserider',
      Items: [
        {
          Period: 'Single',
          CapName: 'Chaserider Single Anytime',
          Area: 'Services 74 and 3',
          AreaLink: '',
          Price: '£2.40',
          ChildPrice: '',
        },
        {
          Period: 'Single',
          CapName: 'Chaserider Single Anytime',
          Area: 'Service 70 & 71',
          AreaLink: '',
          Price: '£3.40',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Chaserider Day Peak',
          Area: 'Services 74 and 3 within and up to the West Midlands County boundary only',
          AreaLink: '',
          Price: '£3.20',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Chaserider Day Anytime',
          Area: 'Service 70 & 71 within and up to the West Midlands County boundary only',
          AreaLink: '',
          Price: '£4.00',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Chaserider Day Anytime',
          Area: 'All areas of services',
          AreaLink: '',
          Price: '£6.30',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Chaserider Walsall Week',
          Area: 'Services 74 and 3 within and up to the West Midlands County boundary only',
          AreaLink: '',
          Price: '£11.60',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: "Chaserider WM's Week",
          Area: 'Service 70 & 71 within and up to the West Midlands County boundary only',
          AreaLink: '',
          Price: '£17.00',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: "Chaserider WM'S Week Off Peak",
          Area: 'Service 70 & 71 within and up to the West Midlands County boundary only',
          AreaLink: '',
          Price: '£14.70',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Chaserider Week',
          Area: 'All areas of services 74 & 3',
          AreaLink: '',
          Price: '£15.50',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Chaserider Week',
          Area: 'All areas of services 70 & 71',
          AreaLink: '',
          Price: '£25.00',
          ChildPrice: '',
        },
      ],
    },
    {
      Company: 'Community Transport',
      Items: [
        {
          Period: 'Day',
          CapName: 'Community Transport Single Anytime',
          Area: 'All routes',
          AreaLink: '',
          Price: '£2.20',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Community Transport Day Anytime',
          Area: 'All routes',
          AreaLink: '',
          Price: '£4.20',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Community Transport Week',
          Area: 'All routes',
          AreaLink: '',
          Price: '£15.80',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Community Transport Week Off-Peak',
          Area: 'All routes',
          AreaLink: '',
          Price: '£12.60',
          ChildPrice: '',
        },
      ],
    },
    {
      Company: 'Diamond',
      Items: [
        {
          Period: 'Day',
          CapName: 'Diamond Single',
          Area: "Diamond WM's",
          AreaLink: '',
          Price: '£2.40',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Diamond Day',
          Area: "Diamond WM's",
          AreaLink: '',
          Price: '£3.80',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Diamond Sandwell & Dudley Day',
          Area: 'Diamond Sandwell & Dudley',
          AreaLink: '',
          Price: '£2.85',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Diamond Walsall Day',
          Area: 'Diamond Walsall',
          AreaLink: '',
          Price: '£3.20',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Diamond West Mids Week',
          Area: "Diamond WM's",
          AreaLink: '',
          Price: '£14.00',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Diamond Sandwell & Dudley Week',
          Area: 'Diamond Sandwell & Dudley',
          AreaLink: '',
          Price: '£10.50',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Diamond Walsall Week',
          Area: 'Diamond Walsall',
          AreaLink: '',
          Price: '£11.60',
          ChildPrice: '',
        },
      ],
    },
    {
      Company: 'Discount Travel',
      Items: [
        {
          Period: 'Day',
          CapName: 'Discount Travel Single Anytime',
          Area: 'All routes',
          AreaLink: '',
          Price: '£2.00',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Discount Travel Day Peak',
          Area: 'All routes',
          AreaLink: '',
          Price: '£4.80',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Discount Travel Day Off-peak',
          Area: 'All routes',
          AreaLink: '',
          Price: '£4.20',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Discount Travel Week',
          Area: 'All routes',
          AreaLink: '',
          Price: '£18.40',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Discount Travel Week Off-Peak',
          Area: 'All routes',
          AreaLink: '',
          Price: '£14.70',
          ChildPrice: '',
        },
      ],
    },
    {
      Company: 'Johnsons Coach and Bus',
      Items: [
        {
          Period: 'Day',
          CapName: 'Johnsons Single Anytime',
          Area: 'All routes in the West Midlands',
          AreaLink: '',
          Price: '£2.00',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Johnsons Day Peak',
          Area: 'All routes in the West Midlands',
          AreaLink: '',
          Price: '£4.80',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Johnsons Day Off-peak',
          Area: 'All routes in the West Midlands',
          AreaLink: '',
          Price: '£4.20',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Johnsons Week',
          Area: 'All routes in the West Midlands',
          AreaLink: '',
          Price: '£18.40',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Johnsons Week Off Peak',
          Area: 'All routes in the West Midlands',
          AreaLink: '',
          Price: '£14.70',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Johnsons Coventry Week',
          Area: 'All routes in Coventry',
          AreaLink: '',
          Price: '£15.80',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Johnsons Coventry Week Off Peak',
          Area: 'All routes in Coventry',
          AreaLink: '',
          Price: '£12.60',
          ChildPrice: '',
        },
      ],
    },
    {
      Company: 'Kevs Cars',
      Description: '*Not valid on Services 147, 318 and 355',
      Items: [
        {
          Period: 'Day',
          CapName: 'Kevs Cars Single',
          Area: 'All West Midlands TfWM contracted services exceptions apply*',
          AreaLink: '',
          Price: '£2.40',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Kevs Cars Day',
          Area: 'All West Midlands TfWM contracted services exceptions apply*',
          AreaLink: '',
          Price: '£4.80',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Kevs Cars Day Off-Peak',
          Area: 'All West Midlands TfWM contracted services exceptions apply*',
          AreaLink: '',
          Price: '£4.20',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Kevs Cars Week',
          Area: 'All West Midlands TfWM contracted services - exceptions apply*',
          AreaLink: '',
          Price: '£18.40',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Kevs Cars Week Off-Peak',
          Area: 'All West Midlands TfWM contracted services exceptions apply*',
          AreaLink: '',
          Price: '£14.70',
          ChildPrice: '',
        },
      ],
    },
    {
      Company: 'Landflight',
      Items: [
        {
          Period: 'Day',
          CapName: 'Landflight Single Anytime',
          Area: 'All routes',
          AreaLink: '',
          Price: '£2.40',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Landflight Day Peak',
          Area: 'All routes',
          AreaLink: '',
          Price: '£4.40',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Landflight Day Off-peak',
          Area: 'All routes',
          AreaLink: '',
          Price: '£4.00',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Landflight Week',
          Area: 'All routes',
          AreaLink: '',
          Price: '£18.00',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Landflight Week Off Peak',
          Area: 'All routes',
          AreaLink: '',
          Price: '£14.70',
          ChildPrice: '',
        },
      ],
    },
    {
      Company: "Let's Go / Travel Express",
      Items: [
        {
          Period: 'Day',
          CapName: "Let's Go Single Anytime",
          Area: 'All routes',
          AreaLink: '',
          Price: '£2.00',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: "Let's Go Day Anytime",
          Area: 'All routes',
          AreaLink: '',
          Price: '£3.00',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Lets Go Week',
          Area: 'All routes',
          AreaLink: '',
          Price: '£10.00',
          ChildPrice: '',
        },
      ],
    },
    {
      Company: 'RK Travel (RK)',
      Items: [
        {
          Period: 'Day',
          CapName: 'RK Travel Single Anytime',
          Area: 'All routes',
          AreaLink: '',
          Price: '£2.00',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'RK Travel Day Peak',
          Area: 'All routes',
          AreaLink: '',
          Price: '£4.80',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'RK Travel Day Off-peak',
          Area: 'All routes',
          AreaLink: '',
          Price: '£4.20',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'RK Travel Week',
          Area: 'All routes',
          AreaLink: '',
          Price: '£18.40',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'RK Travel Week Off-Peak',
          Area: 'All routes',
          AreaLink: '',
          Price: '£14.70',
          ChildPrice: '',
        },
      ],
    },
    {
      Company: 'National Express West Midlands (NXWM)',
      Items: [
        {
          Period: 'Day',
          CapName: 'NX Coventry Single Anytime',
          Area: 'NX Coventry',
          AreaLink: '',
          Price: '£2.20',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'NX Single Anytime',
          Area: 'NX Regional',
          AreaLink: '',
          Price: '£2.40',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'NX Daysaver Peak',
          Area: 'NX Regional',
          AreaLink: '',
          Price: '£4.60',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'NX Daysaver Off-peak',
          Area: 'NX Regional',
          AreaLink: '',
          Price: '£4.00',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'NX Coventry Daysaver Peak',
          Area: 'NX Coventry',
          AreaLink: '',
          Price: '£4.00',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'NX Birmingham LFZ Off-peak',
          Area: 'NX Birmingham LFZ',
          AreaLink: '',
          Price: '£3.00',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'NX Walsall LFZ Anytime',
          Area: 'NX Walsall LFZ',
          AreaLink: '',
          Price: '£3.00',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'NX Sandwell and Dudley LFZ Anytime',
          Area: 'NX Sandwell and Dudley LFZ',
          AreaLink: '',
          Price: '£3.00',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'NX and Metro Off-peak',
          Area: 'NX Regional and All tram',
          AreaLink: '',
          Price: '£5.60',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'NX Week',
          Area: 'NX Regional',
          AreaLink: '',
          Price: '£17.50',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'NX Off Peak Week',
          Area: 'NX Regional',
          AreaLink: '',
          Price: '£14.00',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'NX Coventry Week',
          Area: 'NX Coventry',
          AreaLink: '',
          Price: '£15.00',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'NX Coventry Off Peak Week',
          Area: 'NX Coventry',
          AreaLink: '',
          Price: '£12.00',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'NX Black Country Week',
          Area: 'NX Black Country',
          AreaLink: '',
          Price: '£16.20',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'NX Sandwell & Dudley Week',
          Area: 'NX Sandwell & Dudley',
          AreaLink: '',
          Price: '£11.00',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'NX Walsall Week',
          Area: 'NX Walsall',
          AreaLink: '',
          Price: '£11.00',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'NX + Metro Week',
          Area: 'NX + Metro',
          AreaLink: '',
          Price: '£25.90',
          ChildPrice: '',
        },
      ],
    },
    {
      Company: 'Stagecoach',
      Items: [
        {
          Period: 'Day',
          CapName: 'Stagecoach Single Anytime',
          Area: 'All routes in the West Midlands',
          AreaLink: '',
          Price: '£2.20',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Stagecoach Day Anytime',
          Area: 'All routes in the West Midlands',
          AreaLink: '',
          Price: '£3.50',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Stagecoach Week',
          Area: 'All routes in the West Midlands',
          AreaLink: '',
          Price: '£12.50',
          ChildPrice: '',
        },
      ],
    },
    {
      Company: 'Walsall Community Transport',
      Items: [
        {
          Period: 'Day',
          CapName: 'Walsall CT Single Anytime',
          Area: 'All routes',
          AreaLink: '',
          Price: '£2.40',
          ChildPrice: '',
        },
        {
          Period: 'Day',
          CapName: 'Walsall CT Day Anytime',
          Area: 'All routes',
          AreaLink: '',
          Price: '£3.00',
          ChildPrice: '',
        },
        {
          Period: 'Week',
          CapName: 'Walsall CT Week',
          Area: 'All routes',
          AreaLink: '',
          Price: '£11.60',
          ChildPrice: '',
        },
      ],
    },
  ],
};

export default capsData;
